### ISSUE TITLE
Project description states an invalid PHP compatibility

### ISSUE THREAD

**Issue by abclive** [vaibhavpandeyvpz/jweety#1]
Hi there,

The project description states that it's compatible with PHP >= 5.3 however the parse() function uses hash_equals() which is a PHP >= 5.6 function.

I just thought I would post an issue as a heads up.

Thanks for the lib!

**Comment by vaibhavpandeyvpz** [comment]
For installation on pre 5.6; the package suggests to install [symfony/polyfill-php56](https://github.com/symfony/polyfill-php56). See https://github.com/vaibhavpandeyvpz/jweety/blob/master/composer.json#L33.
