### ISSUE TITLE
Parse error: syntax error, unexpected T_OBJECT_OPERATOR

### ISSUE THREAD

**Issue by johnmichaelrivera** [vaibhavpandeyvpz/jweety#2]
![capture](https://user-images.githubusercontent.com/15009560/47548027-42f4e680-d92a-11e8-9293-b86007c56a8d.PNG)
Why am i getting this error?
I just copy and paste the code
![image](https://user-images.githubusercontent.com/15009560/47547977-0b863a00-d92a-11e8-9bd2-
54bca3cb93a8.png)

**Comment by vaibhavpandeyvpz** [comment]
Your PHP version?

**Comment by johnmichaelrivera** [comment]
PHP 5.4
